name: example
description: Example Flutter Tweet UI app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tweet_ui:
    path: ../
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/tweet_examples/tweet_1_photo.json
    - assets/tweet_examples/tweet_2_photos.json
    - assets/tweet_examples/tweet_3_photos.json
    - assets/tweet_examples/tweet_4_photos.json
    - assets/tweet_examples/tweet_gif.json
    - assets/tweet_examples/tweet_video.json
    - assets/tweet_examples/tweet_with_new_lines_in_text.json
    - assets/tweet_examples/tweet_quote_1_photo.json
    - assets/tweet_examples/tweet_quote_2_photos.json
    - assets/tweet_examples/tweet_quote_3_photos.json
    - assets/tweet_examples/tweet_quote_4_photos.json
    - assets/tweet_examples/tweet_quote_gif.json
    - assets/tweet_examples/tweet_quote_video.json
    - assets/tweet_examples/tweet_bug_gh14.json
    - assets/tweet_examples/tweet_quote_bug_gh14.json
  uses-material-design: true