name: tweet_ui
description: Show Tweets from a Twitter API JSON on Android and iOS. Support for Tweets with 1-4 photos, Video, GIFs, hashtags, mentions, symbols, urls, quoted Tweets and retweets.
version: 2.1.0+1
author: OmniNext team @ Schibsted <michal.kawalko@schibsted.com>
homepage: https://github.com/schibsted/tweet_ui

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">= 1.10.15-pre.148 < 2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  intl: ^0.16.1
  video_player: ^0.10.10
  chewie: ^0.9.10
  photo_view: ^0.9.2
  url_launcher: ^5.4.5
  html_unescape: ^1.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tw__ic_gif_badge.png
    - assets/1.5x/tw__ic_gif_badge.png
    - assets/2.0x/tw__ic_gif_badge.png
    - assets/3.0x/tw__ic_gif_badge.png
    - assets/tw__ic_logo_blue.png
    - assets/1.5x/tw__ic_logo_blue.png
    - assets/2.0x/tw__ic_logo_blue.png
    - assets/3.0x/tw__ic_logo_blue.png
    - assets/tw__ic_play_default.png
    - assets/1.5x/tw__ic_play_default.png
    - assets/2.0x/tw__ic_play_default.png
    - assets/3.0x/tw__ic_play_default.png
    - assets/tw__ic_tweet_verified.png
    - assets/1.5x/tw__ic_tweet_verified.png
    - assets/2.0x/tw__ic_tweet_verified.png
    - assets/3.0x/tw__ic_tweet_verified.png
    - assets/tw__ic_retweet_light.png
    - assets/1.5x/tw__ic_retweet_light.png
    - assets/2.0x/tw__ic_retweet_light.png
    - assets/3.0x/tw__ic_retweet_light.png

  fonts:
    - family: Roboto

      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
